### ISSUE TITLE
Build fails with missing image

### ISSUE THREAD

**Issue by mtreinish** [afrittoli/ciml_talk#2]
When running pdflatex on the the repo it fails to build because it can't locate a missing image file:
`cfc1.png` which is referenced here: https://github.com/afrittoli/ciml_talk/blob/master/ciml.tex#L839 (being used for the background image on the second to last slide) I expect this was just added to the repo on commit when that change was made.

**Comment by afrittoli** [comment]
Fixed by https://github.com/afrittoli/ciml_talk/commit/32ff4fed4de2d5f46a8476e057d86bb7bb3b95c6
